# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './projects/frontend-app'
      # - name: Install dependencies [hh]
      #  run: npm install
      # - name: Compile contracts
      #  run: npx hardhat compile
      #  env:
      #    TESTNET_EOA_PRIVATE_KEY: "${{ secrets.TESTNET_EOA_PRIVATE_KEY }}"
      - name: Install dependencies
        working-directory: ./projects/frontend-app
        run: npm install
      - name: Build
        working-directory: ./projects/frontend-app
        run: npm run build
        env:
          VITE_ENVIRONMENT: "production"
          VITE_ALGOD_TOKEN: ""
          VITE_ALGOD_SERVER: "https://testnet-api.algonode.cloud"
          VITE_ALGOD_PORT: ""
          VITE_ALGOD_NETWORK: "testnet"
          VITE_INDEXER_TOKEN: ""
          VITE_INDEXER_SERVER: "https://testnet-idx.algonode.cloud"
          VITE_INDEXER_PORT: ""
          VITE_DISPENSER: 680738109
          VITE_USDCA: 680738127
          VITE_EVENT_FACTORY_CONTRACT: 680738089
          VITE_GEOMAP_API_KEY: "${{ secrets.VITE_GEOMAP_API_KEY }}"
          VITE_WALLET_CONNECT_ID: "${{ secrets.VITE_WALLET_CONNECT_ID }}"
          VITE_PINATA_JWT: "${{ secrets.VITE_PINATA_JWT }}"
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './projects/frontend-app/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
